export type RFS = {
    id: number,
    createdAt: Date,
    mode1: number | null,
    mode2: number | null,
    mode3: number | null,
    mode4: number | null,
    mode5: number | null,
    mode6: number | null,
    mode7: number | null,
    mode8: number | null,
    mode9: number | null,
    mode10: number | null,
    userId: number,
}